### ISSUE TITLE
Hashing in requirements.txt causes problems when building Execution Environments with ansible-builder

### ISSUE THREAD

**Issue by tarmael** [zscaler/ziacloud-ansible#52]
## Describe the bug
From what I understand using ansible-builder v3.1.0, after the collection installation step, ansible-builder rebundles the requirements from all of the collections into a new requirements.txt

Because zscaler.ziacloud's requirements.txt is in hashing mode, this forces pip into using hashing mode for all of the pypi packages, which fails because none of the other collections using hashes for their requirements.

## Possible solution

Use version requirements like:
```
aiosignal==1.3.1 ; python_version >= "3.9" and python_version < "4.0"
```

Remove hashing like:
```
    --hash=sha256:fbc6264158392bad9df19537e872d476f7c57adf718944cc1e4495cbabf38e2a \
    --hash=sha256:fe2fb38c2ed905a2582948e2de560675e9dfbee94c6d5ccdb1301c6d0a5bf092 \
```

## Steps to reproduce

This fails:
execution-environment.yml

```
---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

# Custom package manager path for the RHEL based images
options:
  package_manager_path: /usr/bin/microdnf

dependencies:
  python_interpreter:
    package_system: python3.11-devel
    python_path: /usr/bin/python3.11
  ansible_core:
    package_pip: ansible-core>=2.15,<2.17
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
      - zscaler.ziacloud
      - ansible.windows
      - microsoft.ad
      - community.general
  python:
    - pywinrm[kerberos]
    - urllib3
    - zscaler-sdk-python
```

This succeeds by moving the zscaler.ziacloud collection to a post installation task:
execution-environment.yml

```
---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

# Custom package manager path for the RHEL based images
options:
  package_manager_path: /usr/bin/microdnf

additional_build_steps:
  append_final:
    - RUN ansible-galaxy collection install zscaler.ziacloud --collections-path "/usr/share/ansible/collections"

dependencies:
  python_interpreter:
    package_system: python3.11-devel
    python_path: /usr/bin/python3.11
  ansible_core:
    package_pip: ansible-core>=2.15,<2.17
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
      - ansible.windows
      - microsoft.ad
      - community.general
  python:
    - pywinrm[kerberos]
    - urllib3
    - zscaler-sdk-python
```
