### ISSUE TITLE
'Response' object has no attribute 'to_list'

### ISSUE THREAD

**Issue by borgermeister** [zscaler/ziacloud-ansible#64]
## Describe the bug

I am unable to run a simple playbook with the ZIA Ansible module.

## Expected behavior

The playbook should return the URL Category 'OTHER_ADULT_MATERIAL'.

## Current behavior

```shell
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_zscaler.ziacloud.zia_url_categories_info_payload_ld_x3q5o/ansible_zscaler.ziacloud.zia_url_categories_info_payload.zip/ansible_collections/zscaler/ziacloud/plugins/modules/zia_url_categories_info.py", line 212, in main
    core(module)
  File "/tmp/ansible_zscaler.ziacloud.zia_url_categories_info_payload_ld_x3q5o/ansible_zscaler.ziacloud.zia_url_categories_info_payload.zip/ansible_collections/zscaler/ziacloud/plugins/modules/zia_url_categories_info.py", line 177, in core
    categories = client.url_categories.list_categories().to_list()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Response' object has no attribute 'to_list'
fatal: [localhost]: FAILED! => changed=false 
  invocation:
    module_args:
      api_key: null
      cloud: null
      configured_name: null
      id: OTHER_ADULT_MATERIAL
      password: null
      provider:
        api_key: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        cloud: zscalertwo
        password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        sandbox_token: null
        username: xxxx
      sandbox_token: null
      username: null
  msg: '''Response'' object has no attribute ''to_list'''
```

## Steps to reproduce

Run the following playbook:

```yaml
---

- name: URL Categories
  hosts: localhost
  connection: local

  vars:
    zscaler_zia:
      username: 'xxx'
      password: 'xxx'
      api_key: 'xxxx'  # https://admin.zscalertwo.net/#administration/api-key-management
      cloud: 'zscalertwo'

  tasks:
    - name: Gather Information Details of all URL Categories
      zscaler.ziacloud.zia_url_categories_info:
        provider: '{{ zscaler_zia }}'
        id: "OTHER_ADULT_MATERIAL"
```

## Your Environment

- Collection: zscaler.ziacloud 1.3.5  
- Python: 3.12.8
- Ansible: core 2.18.4
- Zscaler SDK Python Library & version: zscaler-sdk-python 0.10.5

**Comment by borgermeister** [comment]
I use a virtual environment created with Devbox and Poetry.

```shell
# content of devbox.json
{
  "$schema": "https://raw.githubusercontent.com/jetify-com/devbox/0.14.0/.schema/devbox.schema.json",
  "packages": [
    "ansible@latest",
    "poetry@latest"
  ],
  "shell": {
    "init_hook": [
      "poetry install --no-root",
      "source .venv/bin/activate"
     ]
  }
}
```

```shell
# content of pyproject.toml
[project]
name = "Ansible-ZIA-test"
version = "0.1.0"
description = "Test environment"
authors = [
    {name = "Bjørn-Vegar Borge",email = "bvborge@gmail.com"}
]

[tool.poetry.dependencies]
python = "^3.12"
zscaler-sdk-python = "~0"
```

**Comment by willguibr** [comment]
@borgermeister 
Based on our tests using the exact same playbook you provided we had no issues executing the code with the latest collection version.
Please raise a case via Zscaler Global Support and make mention of this GitHub Issue number, so the issue can be looked at and escalated if needed. Make sure that the requirements.txt is has been executed when the collection was installed so that all dependencies are also installed accordingly.

Zscaler DevRel

![Image](https://github.com/user-attachments/assets/8333d7f9-0bbc-4551-964e-9c34c9d66973)

**Comment by borgermeister** [comment]
Perhaps a dumb question but the documentation says that the 'api_key' should be a string that contains the obfuscated API key. Does that mean that I cannot use the API key shown in the ZIA WebUI directly in my playbook?

**Comment by willguibr** [comment]
Nothing to do with the collection. The api key obfuscation is handled at the Python SDK level. You simply need to pass the string you obtain from your ZIA portal. Please try to use a different environment instead. From our standpoint the collection is working as designed based on our tests using the same playbook. 

Zscaler DevRel

**Comment by willguibr** [comment]
@borgermeister Please upgrade the collection to the latest version v2.0.0.
Prior to attempting to use please refer to the documentation for authentication details.

Zscaler DevRel

**Comment by borgermeister** [comment]
Hi

I've upgraded zscaler.ziacloud collection to v2.0.0 and zscaler-sdk-python to v1.2.2.

It seems to be almost working now, but I'm not sure how the authentication is supposed to work.

```yaml
# Provider
zscaler_zia:
  client_id: 'xxxx'
  client_secret: 'xxxx'
  vanity_domain: 'our_company_name'
```

```yaml
# Simple playbook
- name: URL Categories
  hosts: localhost
  connection: local

  tasks:

    - name: Gather Information Details of all URL Categories
      zscaler.ziacloud.zia_url_categories_info:
        provider: '{{ zscaler_zia }}'
```

```shell
fatal: [localhost]: FAILED! => 
    changed: false
    msg: |-
        Error retrieving URL categories: {
          "status": 401,
          "code": null,
          "message": null,
          "url": "https://api.zsapi.net/zia/api/v1/urlCategories"
        }
```
