### ISSUE TITLE
'Response' object has no attribute 'to_list'

### ISSUE THREAD

**Issue by Pskaf-Moost** [zscaler/ziacloud-ansible#65]
## Describe the bug

I am getting the following error while trying to add a custom URL Category onto my Zscaler Beta tenant : 'Response' object has no attribute 'to_list'

## Expected behavior
It should create a new URL Category

## Current behavior
Nothing happens and I got the erreor : 'Response' object has no attribute 'to_list'

## Steps to reproduce

Here is my code : 

```
- name: Create a URL Category
  environment:
    https_proxy: our_proxy
  zscaler.ziacloud.zia_url_categories:
    api_key: "{{zscaler_api}}"
    password: "{{zscaler_password}}"
    username: "{{zscaler_username}}"
    cloud: zscalerbeta
    super_category: USER_DEFINED
    configured_name: "SomeText"
    description: "SomeText"
    custom_category: true
    editable: true
    type: URL_CATEGORY
    db_categorized_urls:
      - .test.com
    urls: 
      - .test2.com
```

## Your Environment

python version = 3.12.6 (main, Sep 12 2024, 21:15:48) [GCC 13.2.1 20240309] (/usr/local/bin/python3.12)
jinja version = 3.1.6
libyaml = True
Collection zscaler.ziacloud 1.3.5
