### ISSUE TITLE
zscaler.ziacloud.zia_ssl_inspection_rules module use name and not id

### ISSUE THREAD

**Issue by borgermeister** [zscaler/ziacloud-ansible#69]
# Feature request

I would like all of the modules to be able to use the displayed name of groups, cloud application, url categories instead of using the ID.

I would like to use this format:
  groups: Contractors
  url_categories: 'Professional Services'
  cloud_applications: 'Microsoft Login Services'

But now I have to do it this way:
  groups: 129685619
  url_categories: PROFESSIONAL_SERVICES
  cloud_applications: MSLOGINSERVICES

I can of course, as a workaround, use Postman to list all groups to get the correct ID, and URL Categories/Cloud Applications to get the correct syntax.

# Example playbook

```yaml
# ziacloud.zia_ssl_inspection_rules_vars.yaml
zia_ssl_inspection_rules:
  - name: 'SSL Inspection Rule example'
    order: 10
    description: 'Some useful description'
    enabled: true
    groups:
      - 129685619
    url_categories:
      - PROFESSIONAL_SERVICES
    cloud_applications:
      - MSLOGINSERVICES
    action:
      type: DECRYPT  # Options: BLOCK, DECRYPT, DO_NOT_DECRYPT
      override_default_certificate: false
      show_eun: false
      show_eunatp: false
      decrypt_sub_actions:
        block_ssl_traffic_with_no_sni_enabled: true
        block_undecrypt: true
        http2_enabled: true
        min_client_tls_version: CLIENT_TLS_1_2
        min_server_tls_version: SERVER_TLS_1_2
        ocsp_check: true
        server_certificates: BLOCK  # Options: ALLOW, BLOCK, PASS_THRU
    state: present
```

```yaml
# SSL rule playbook
- name: Create SSL Inspection Rules
  zscaler.ziacloud.zia_ssl_inspection_rules:
    provider: '{{ zscaler_zia }}'
    order: '{{ item.order }}'
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    enabled: '{{ item.enabled }}'
    groups: '{{ item.groups | default(omit) }}'
    url_categories: '{{ item.url_categories | default(omit) }}'
    cloud_applications: '{{ item.cloud_applications | default(omit) }}'
    action:
      type: '{{ item.action.type }}'
      override_default_certificate: '{{ item.action.override_default_certificate | default(false) }}'
      show_eun: '{{ item.action.show_eun | default(false) }}'
      show_eunatp: '{{ item.action.show_eunatp | default(false) }}'
      decrypt_sub_actions:
        block_ssl_traffic_with_no_sni_enabled: '{{ item.action.decrypt_sub_actions.block_ssl_traffic_with_no_sni_enabled | default(omit) }}'
        block_undecrypt: '{{ item.action.decrypt_sub_actions.block_undecrypt | default(omit) }}'
        http2_enabled: '{{ item.action.decrypt_sub_actions.http2_enabled | default(omit) }}'
        min_client_tls_version: '{{ item.action.decrypt_sub_actions.min_client_tls_version | default(omit) }}'
        min_server_tls_version: '{{ item.action.decrypt_sub_actions.min_server_tls_version | default(omit) }}'
        ocsp_check: '{{ item.action.decrypt_sub_actions.ocsp_check | default(omit) }}'
        server_certificates: '{{ item.action.decrypt_sub_actions.server_certificates | default(omit) }}'
    road_warrior_for_kerberos: '{{ item.action.road_warrior_for_kerberos | default(false) }}'
    state: '{{ item.state }}'
  loop: '{{ zia_ssl_inspection_rules }}'
```
