### ISSUE TITLE
zscaler.ziacloud.zia_ssl_inspection_rules module action type

### ISSUE THREAD

**Issue by borgermeister** [zscaler/ziacloud-ansible#70]
I have an issue when using the zscaler.ziacloud.zia_ssl_inspection_rules module, and more specific using the different types of action - BLOCK, DECRYPT, DO_NOT_DECRYPT.

I have configured the task to go through a loop so I can create several rules using the same task. The problem is that I cannot have `decrypt_sub_actions` and `do_not_decrypt_sub_actions` active in the same task, even though I choose action `DECRYPT` or `DO_NOT_DECRYPT`.

# Example

## Variables

```yaml
zia_ssl_inspection_rules:
  - name: 'SSL Inspection Rule'
    order: 10
    description: 'Give a useful description'
    enabled: true
    groups:
      - 129685619
    url_categories:
      - PROFESSIONAL_SERVICES
    cloud_applications:
      - MSLOGINSERVICES
    action:
      type: DECRYPT  # Options: BLOCK, DECRYPT, DO_NOT_DECRYPT
      override_default_certificate: false
      show_eun: false
      show_eunatp: false
      decrypt_sub_actions:
        block_ssl_traffic_with_no_sni_enabled: true
        block_undecrypt: true
        http2_enabled: true
        min_client_tls_version: CLIENT_TLS_1_2
        min_server_tls_version: SERVER_TLS_1_2
        ocsp_check: true
        server_certificates: BLOCK  # Options: ALLOW, BLOCK, PASS_THRU
      # do_not_decrypt_sub_actions:
      #   block_ssl_traffic_with_no_sni_enabled: true
      #   bypass_other_policies: false
      #   min_tls_version: SERVER_TLS_1_2
      #   ocsp_check: true
      #   server_certificates: BLOCK  # Options: ALLOW, BLOCK
    state: present
```

## Playbook

```yaml
- name: Create SSL Inspection Rules
  zscaler.ziacloud.zia_ssl_inspection_rules:
    provider: '{{ zscaler_zia }}'
    order: '{{ item.order }}'
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    enabled: '{{ item.enabled }}'
    groups: '{{ item.groups | default(omit) }}'
    url_categories: '{{ item.url_categories | default(omit) }}'
    cloud_applications: '{{ item.cloud_applications | default(omit) }}'
    action:
      type: '{{ item.action.type }}'
      override_default_certificate: '{{ item.action.override_default_certificate | default(false) }}'
      show_eun: '{{ item.action.show_eun | default(false) }}'
      show_eunatp: '{{ item.action.show_eunatp | default(false) }}'
      decrypt_sub_actions:
        block_ssl_traffic_with_no_sni_enabled: '{{ item.action.decrypt_sub_actions.block_ssl_traffic_with_no_sni_enabled | default(omit) }}'
        block_undecrypt: '{{ item.action.decrypt_sub_actions.block_undecrypt | default(omit) }}'
        http2_enabled: '{{ item.action.decrypt_sub_actions.http2_enabled | default(omit) }}'
        min_client_tls_version: '{{ item.action.decrypt_sub_actions.min_client_tls_version | default(omit) }}'
        min_server_tls_version: '{{ item.action.decrypt_sub_actions.min_server_tls_version | default(omit) }}'
        ocsp_check: '{{ item.action.decrypt_sub_actions.ocsp_check | default(omit) }}'
        server_certificates: '{{ item.action.decrypt_sub_actions.server_certificates | default(omit) }}'
      # do_not_decrypt_sub_actions:
      #   block_ssl_traffic_with_no_sni_enabled: '{{ item.action.do_not_decrypt_sub_actions.block_ssl_traffic_with_no_sni_enabled | default(omit) }}'
      #   bypass_other_policies: '{{ item.action.do_not_decrypt_sub_actions.bypass_other_policies | default(omit) }}'
      #   min_tls_version: '{{ item.action.do_not_decrypt_sub_actions.min_tls_version | default(omit) }}'
      #   ocsp_check: '{{ item.action.do_not_decrypt_sub_actions.ocsp_check | default(omit) }}'
      #   server_certificates: '{{ item.action.do_not_decrypt_sub_actions.server_certificates | default(omit) }}'
    road_warrior_for_kerberos: '{{ item.action.road_warrior_for_kerberos | default(false) }}'
    state: '{{ item.state }}'
  loop: '{{ zia_ssl_inspection_rules }}'
```

Running the task is working as expected, but if I uncomment everything under `do_not_decrypt_sub_actions` both in the task and in the variables I get this error:

```yaml
[WARNING]: Difference detected in action. Current: {'type': 'DECRYPT', 'decrypt_sub_actions': {'server_certificates': 'BLOCK', 'ocsp_check': True, 'block_ssl_traffic_with_no_sni_enabled': True, 'min_client_tls_version': 'CLIENT_TLS_1_2', 'min_server_tls_version': 'SERVER_TLS_1_2', 'block_undecrypt': True, 'http2_enabled': True}}, Desired: {'type': 'DECRYPT', 'decrypt_sub_actions':
{'block_ssl_traffic_with_no_sni_enabled': True, 'block_undecrypt': True, 'http2_enabled': True, 'min_client_tls_version': 'CLIENT_TLS_1_2', 'min_server_tls_version': 'SERVER_TLS_1_2', 'ocsp_check': True, 'server_certificates': 'BLOCK'}, 'do_not_decrypt_sub_actions': {'block_ssl_traffic_with_no_sni_enabled': True, 'min_tls_version': 'SERVER_TLS_1_2', 'ocsp_check': True, 'server_certificates': 'BLOCK'}}
[WARNING]: Payload Update for SDK: {'rule_id': 1448458, 'name': 'SSL Inspection Rule', 'description': 'Give a useful description', 'enabled': True, 'rank': 7, 'order': 10, 'action': {'type': 'DECRYPT', 'decrypt_sub_actions': {'block_ssl_traffic_with_no_sni_enabled': True, 'block_undecrypt': True, 'http2_enabled': True, 'min_client_tls_version': 'CLIENT_TLS_1_2', 'min_server_tls_version': 'SERVER_TLS_1_2',
'ocsp_check': True, 'server_certificates': 'BLOCK'}, 'do_not_decrypt_sub_actions': {'block_ssl_traffic_with_no_sni_enabled': True, 'min_tls_version': 'SERVER_TLS_1_2', 'ocsp_check': True, 'server_certificates': 'BLOCK'}}, 'groups': [129685619], 'road_warrior_for_kerberos': False, 'cloud_applications': ['MSLOGINSERVICES'], 'url_categories': ['PROFESSIONAL_SERVICES']}
failed: [localhost] (item={'name': 'SSL Inspection Rule', 'order': 10, 'description': 'Give a useful description', 'enabled': True, 'groups': [129685619], 'url_categories': ['PROFESSIONAL_SERVICES'], 'cloud_applications': ['MSLOGINSERVICES'], 'action': {'type': 'DECRYPT', 'override_default_certificate': False, 'show_eun': False, 'show_eunatp': False, 'decrypt_sub_actions': {'block_ssl_traffic_with_no_sni_enabled': True, 'block_undecrypt': True, 'http2_enabled': True, 'min_client_tls_version': 'CLIENT_TLS_1_2', 'min_server_tls_version': 'SERVER_TLS_1_2', 'ocsp_check': True, 'server_certificates': 'BLOCK'}, 'do_not_decrypt_sub_actions': {'block_ssl_traffic_with_no_sni_enabled': True, 'bypass_other_policies': False, 'min_tls_version': 'SERVER_TLS_1_2', 'ocsp_check': True, 'server_certificates': 'BLOCK'}}, 'state': 'present'}) => 
    ansible_loop_var: item
    changed: false
    item:
        action:
            decrypt_sub_actions:
                block_ssl_traffic_with_no_sni_enabled: true
                block_undecrypt: true
                http2_enabled: true
                min_client_tls_version: CLIENT_TLS_1_2
                min_server_tls_version: SERVER_TLS_1_2
                ocsp_check: true
                server_certificates: BLOCK
            do_not_decrypt_sub_actions:
                block_ssl_traffic_with_no_sni_enabled: true
                bypass_other_policies: false
                min_tls_version: SERVER_TLS_1_2
                ocsp_check: true
                server_certificates: BLOCK
            override_default_certificate: false
            show_eun: false
            show_eunatp: false
            type: DECRYPT
        cloud_applications:
        - MSLOGINSERVICES
        description: Give a useful description
        enabled: true
        groups:
        - 129685619
        name: SSL Inspection Rule
        order: 10
        state: present
        url_categories:
        - PROFESSIONAL_SERVICES
    msg: |-
        Error updating rule: {
          "status": 400,
          "code": "INVALID_INPUT_ARGUMENT",
          "message": "SSLAction values are invalid.",
          "url": "https://api.zsapi.net/zia/api/v1/sslInspectionRules/1448458"
        }
```

What I would like to module to do is using some conditional checks that if I choose action `DECRYPT` it ignores everything under `do_not_decrypt_sub_actions`. And the same goes the other way if I choose action `DO_NOT_DECRYPT` it should ignore everything under `ecrypt_sub_actions`.

**Comment by willguibr** [comment]
@borgermeister ZIA SSL Inspection Rules only support **one action type per rule** — either `BLOCK`, `DECRYPT`, or `DO_NOT_DECRYPT`. Each action has its own optional sub-actions (`decrypt_sub_actions` or `do_not_decrypt_sub_actions`), but **you cannot mix both** in a single rule.

This limitation is enforced by the API and is consistent with the ZIA Admin UI: if you can't configure multiple action types in the same rule in the UI, the same restriction applies when using automation like Ansible or Terraform.

If you need different behaviors, you should define **separate rules** for each action type. For example:
- One rule with `type: DECRYPT` and `decrypt_sub_actions`
- Another rule with `type: DO_NOT_DECRYPT` and `do_not_decrypt_sub_actions`

Zscaler DevRel

**Comment by borgermeister** [comment]
I've done it this way and it seems to be working as expected..

```yaml
---

- name: Create SSL Inspection Rules - Decrypt
  when: item.action.type == 'DECRYPT'
  zscaler.ziacloud.zia_ssl_inspection_rules:
    provider: '{{ zscaler_zia }}'
    order: '{{ item.order }}'
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    enabled: '{{ item.enabled }}'
    groups: '{{ item.groups | default(omit) }}'
    url_categories: '{{ item.url_categories | default(omit) }}'
    cloud_applications: '{{ item.cloud_applications | default(omit) }}'
    action:
      type: '{{ item.action.type }}'
      override_default_certificate: '{{ item.action.override_default_certificate | default(false) }}'
      show_eun: '{{ item.action.show_eun | default(false) }}'
      show_eunatp: '{{ item.action.show_eunatp | default(false) }}'
      decrypt_sub_actions:
        block_ssl_traffic_with_no_sni_enabled: '{{ item.action.decrypt_sub_actions.block_ssl_traffic_with_no_sni_enabled | default(omit) }}'
        block_undecrypt: '{{ item.action.decrypt_sub_actions.block_undecrypt | default(omit) }}'
        http2_enabled: '{{ item.action.decrypt_sub_actions.http2_enabled | default(omit) }}'
        min_client_tls_version: '{{ item.action.decrypt_sub_actions.min_client_tls_version | default(omit) }}'
        min_server_tls_version: '{{ item.action.decrypt_sub_actions.min_server_tls_version | default(omit) }}'
        ocsp_check: '{{ item.action.decrypt_sub_actions.ocsp_check | default(omit) }}'
        server_certificates: '{{ item.action.decrypt_sub_actions.server_certificates | default(omit) }}'
    road_warrior_for_kerberos: '{{ item.action.road_warrior_for_kerberos | default(false) }}'
    state: '{{ item.state }}'
  loop: '{{ zia_ssl_inspection_rules }}'

- name: Create SSL Inspection Rules - Do Not Decrypt
  when: item.action.type == 'DO_NOT_DECRYPT'
  zscaler.ziacloud.zia_ssl_inspection_rules:
    provider: '{{ zscaler_zia }}'
    order: '{{ item.order }}'
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    enabled: '{{ item.enabled }}'
    groups: '{{ item.groups | default(omit) }}'
    url_categories: '{{ item.url_categories | default(omit) }}'
    cloud_applications: '{{ item.cloud_applications | default(omit) }}'
    action:
      type: '{{ item.action.type }}'
      override_default_certificate: '{{ item.action.override_default_certificate | default(false) }}'
      show_eun: '{{ item.action.show_eun | default(false) }}'
      show_eunatp: '{{ item.action.show_eunatp | default(false) }}'
      do_not_decrypt_sub_actions:
        block_ssl_traffic_with_no_sni_enabled: '{{ item.action.do_not_decrypt_sub_actions.block_ssl_traffic_with_no_sni_enabled | default(omit) }}'
        bypass_other_policies: '{{ item.action.do_not_decrypt_sub_actions.bypass_other_policies | default(omit) }}'
        min_tls_version: '{{ item.action.do_not_decrypt_sub_actions.min_tls_version | default(omit) }}'
        ocsp_check: '{{ item.action.do_not_decrypt_sub_actions.ocsp_check | default(omit) }}'
        server_certificates: '{{ item.action.do_not_decrypt_sub_actions.server_certificates | default(omit) }}'
    road_warrior_for_kerberos: '{{ item.action.road_warrior_for_kerberos | default(false) }}'
    state: '{{ item.state }}'
  loop: '{{ zia_ssl_inspection_rules }}'

- name: Create SSL Inspection Rules - Block
  when: item.action.type == 'BLOCK'
  zscaler.ziacloud.zia_ssl_inspection_rules:
    provider: '{{ zscaler_zia }}'
    order: '{{ item.order }}'
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    enabled: '{{ item.enabled }}'
    groups: '{{ item.groups | default(omit) }}'
    url_categories: '{{ item.url_categories | default(omit) }}'
    cloud_applications: '{{ item.cloud_applications | default(omit) }}'
    action:
      type: '{{ item.action.type }}'
      override_default_certificate: '{{ item.action.override_default_certificate | default(false) }}'
      show_eun: '{{ item.action.show_eun | default(false) }}'
      show_eunatp: '{{ item.action.show_eunatp | default(false) }}'
    road_warrior_for_kerberos: '{{ item.action.road_warrior_for_kerberos | default(false) }}'
    state: '{{ item.state }}'
  loop: '{{ zia_ssl_inspection_rules }}'
```
