### ISSUE TITLE
zia_user_management_department_info module returns error

### ISSUE THREAD

**Issue by borgermeister** [zscaler/ziacloud-ansible#71]
## Describe the bug

When I run a simple playbook to retrieve info about all departments I only get an error.

```yaml
# Playbook
- name: Gather Information Details for all Departments
  zscaler.ziacloud.zia_user_management_department_info:
    provider: '{{ zscaler_zia }}'
```

The error I receive:

```yaml
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_zscaler.ziacloud.zia_user_management_department_info_payload_aecwvy04/ansible_zscaler.ziacloud.zia_user_management_department_info_payload.zip/ansible_collections/zscaler/ziacloud/plugins/modules/zia_user_management_department_info.py", line 169, in main
    core(module)
  File "/tmp/ansible_zscaler.ziacloud.zia_user_management_department_info_payload_aecwvy04/ansible_zscaler.ziacloud.zia_user_management_department_info_payload.zip/ansible_collections/zscaler/ziacloud/plugins/modules/zia_user_management_department_info.py", line 127, in core
    result, err = collect_all_items(
                  ^^^^^^^^^^^^^^^^^^
  File "/tmp/ansible_zscaler.ziacloud.zia_user_management_department_info_payload_aecwvy04/ansible_zscaler.ziacloud.zia_user_management_department_info_payload.zip/ansible_collections/zscaler/ziacloud/plugins/module_utils/utils.py", line 498, in collect_all_items
    page, err = resp.next()
    ^^^^^^^^^
ValueError: too many values to unpack (expected 2)
fatal: [localhost]: FAILED! => 
    changed: false
    invocation:
        module_args:
            api_key: null
            client_id: null
            client_secret: null
            cloud: null
            id: null
            name: null
            password: null
            private_key: null
            provider:
                api_key: null
                client_id: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
                client_secret: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
                cloud: null
                password: null
                private_key: null
                sandbox_cloud: null
                sandbox_token: null
                use_legacy_client: false
                username: null
                vanity_domain: our_company
            sandbox_cloud: null
            sandbox_token: null
            use_legacy_client: false
            username: null
            vanity_domain: null
    msg: too many values to unpack (expected 2)
```

The same error is also on the `zia_user_management_groups_info` module.

## Expected behavior

The module should return all departments with name and ID.

## Steps to reproduce

Run the playbook.

## Your Environment

- Collection: zscaler.ziacloud v2.0.0
- Python: 3.12.8
- Ansible: core 2.18.5
- Zscaler SDK Python Library & version: zscaler-sdk-python v1.2.4

**Comment by willguibr** [comment]
Please upgrade to version v2.0.1

Zscaler DevRel

**Comment by borgermeister** [comment]
Thank you for your reply. I upgraded to 2.0.1 any everything is working now.

As a workaround to get the ID of each group/department I created this playbook..

```yaml
- name: Gather Information Details for all Departments
  zscaler.ziacloud.zia_user_management_department_info:
    provider: '{{ zscaler_zia }}'
  register: id_departments

- name: Register each Department ID as a separate variable
  set_fact:
    department_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}: "{{ item.id }}"
  loop: "{{ id_departments.departments}}"
```

This way I can configure my variables like this..

```yaml
zia_url_filtering_rules:
    groups:
      - '{{ group_borgermeister }}'
    departments:
      - '{{ department_borgermeisterit }}'
```
