### ISSUE TITLE
zia_cloud_applications_info - too many values to unpack

### ISSUE THREAD

**Issue by borgermeister** [zscaler/ziacloud-ansible#77]
When I run the following task I get an error:

Task:
```yaml
- name: Gather Information Details for all Cloud Applications - SSL Policy
  zscaler.ziacloud.zia_cloud_applications_info:
    provider: '{{ zscaler_zia }}'
    mode: ssl_policy
  register: cloud_applications
```

The error message:
```yaml
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_zscaler.ziacloud.zia_cloud_applications_info_payload_w0qht7g_/ansible_zscaler.ziacloud.zia_cloud_applications_info_payload.zip/ansible_collections/zscaler/ziacloud/plugins/modules/zia_cloud_applications_info.py", line 186, in core
    page, error = response.next()
    ^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
fatal: [localhost]: FAILED! => 
    changed: false
    invocation:
        module_args:
            api_key: null
            app_class: null
            client_id: null
            client_secret: null
            cloud: null
            group_results: null
            mode: ssl_policy
            password: null
            private_key: null
            provider:
                api_key: null
                client_id: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
                client_secret: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
                cloud: null
                password: null
                private_key: null
                sandbox_cloud: null
                sandbox_token: null
                use_legacy_client: false
                username: null
                vanity_domain: xxxx
            sandbox_cloud: null
            sandbox_token: null
            use_legacy_client: false
            username: null
            vanity_domain: null
    msg: too many values to unpack (expected 2)
```

I get the same error when trying mode: app_policy.

Ansible core                    2.18.5
zscaler-sdk-python        1.4.3
zscaler.ziacloud              2.0.3
