### ISSUE TITLE
zscaler.ziacloud.zia_url_filtering_rules module throws 400

### ISSUE THREAD

**Issue by Ment-LLB** [zscaler/ziacloud-ansible#78]
## Describe the bug

Hello,

we currently try to implement the ziacloud ansible module. We want to create filter rules via ansible. 

Everytime i try to create a filter rule, i get the response: msg: 'Error creating rule: Request failed with status 400'

## Expected behavior

The URL filtering rule gets created. 

## Current behavior

The module fails with the response: 

`msg: 'Error creating rule: Request failed with status 400'
invocation:
  module_args:
    provider:
      username: zscaler.api@test.com
      password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      api_key: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      cloud: zscloud
      use_legacy_client: true
      sandbox_token: null
      sandbox_cloud: null
      client_id: null
      client_secret: null
      private_key: null
      vanity_domain: null
    name: test
    use_legacy_client: false
    rank: 7
    state: present
    username: null
    password: null
    api_key: null
    cloud: null
    sandbox_token: null
    sandbox_cloud: null
    client_id: null
    client_secret: null
    private_key: null
    vanity_domain: null
    id: null
    description: null
    enabled: null
    order: null
    action: null
    protocols: null
    request_methods: null
    user_agent_types: null
    locations: null
    groups: null
    departments: null
    users: null
    override_users: null
    override_groups: null
    block_override: null
    url_categories: null
    time_quota: null
    size_quota: null
    time_windows: null
    location_groups: null
    labels: null
    device_trust_levels: null
    user_risk_score_levels: null
    device_groups: null
    devices: null
    validity_start_time: null
    validity_end_time: null
    validity_time_zone_id: null
    enforce_time_validity: null
    end_user_notification_url: null
    cipa_rule: null
    workload_groups: null
    cbi_profile: null
warnings:
  - 'Difference detected in name. Current: None, Desired: test'
  - 'Difference detected in rank. Current: None, Desired: 7'
  - 'Difference detected in block_override. Current: None, Desired: False'
  - 'Difference detected in enforce_time_validity. Current: None, Desired: False'
  - >-
    Final payload being sent to SDK: {'name': 'test', 'rank': 7,
    'enforce_time_validity': False, 'block_override': False}
  - Creating new rule as no existing rule found
  - >-
    Payload for SDK: {'name': 'test', 'rank': 7, 'block_override': False,
    'enforce_time_validity': False}
_ansible_no_log: false
changed: false`

## Steps to reproduce

Implementation looks like following

`  - name: "Create the filtering rule"
    zscaler.ziacloud.zia_url_filtering_rules:
      provider: '{{ zia_cloud }}'
      name: "test"`

The provider works, as we can get all informations about the existing URL filtering rules. 

## Your Environment

Red Hat Ansible
ziacloud 2.0.3 Ansible module
Zscaler SDK Python Library 1.4.3 

The api role has the permissions full on URL categories, locations and the URL & Cloud App Control.

**Comment by willguibr** [comment]
@Ment-LLB I am not entirely sure which playbook configuration you're using as you haven't provide the exact code.
Either way, for the little we could infer, you are missing important attributes in the playbook, which then makes the payload being rejected by the API with a 400. Please review the documentation accordingly, and ensure that all minimum required attributes are being provided correctly.

See below an example:
```yml
  tasks:
    - name: Create basic URL Filtering Rule
      zscaler.ziacloud.zia_url_filtering_rules:
        provider:
          username: ""
          password: "{{ lookup('env', 'ZIA_PASSWORD') }}"
          api_key: "{{ lookup('env', 'ZIA_API_KEY') }}"
          cloud: "zscloud"
          use_legacy_client: true
        name: "test_rule"
        rank: 7
        order: 1
        action: BLOCK
        enabled: true
        block_override: false
        enforce_time_validity: false
        protocols:
          - TUNNELSSL_RULE
          - HTTP_PROXY
          - FOHTTP_RULE
          - FTP_RULE
          - SSL_RULE
          - TUNNEL_RULE
          - HTTPS_RULE
          - WEBSOCKETSSL_RULE
          - WEBSOCKET_RULE
          - HTTP_RULE
          - DOHTTPS_RULE
        request_methods:
          - CONNECT
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - OTHER
          - POST
          - PUT
          - TRACE
          - PROPFIND
          - PROPPATCH
          - MKCOL
          - MOVE
          - LOCK
          - UNLOCK
          - PATCH
          - COPY
```

If you have any further questions please contact Zscaler support for assistance.
