### ISSUE TITLE
zia_url_categories / urls missing

### ISSUE THREAD

**Issue by borgermeister** [zscaler/ziacloud-ansible#80]
Hi

When using the module `zia_url_categories` I get an error when creating a new custom URL category.
I usually only want to use `db_categorized_urls` but I get an error if `urls` is empty.

If I create the URL category with a bogus URL the first time I do not get an error, and the next time I run the playbook I can remove `urls` completely and everything is working as expected.

```yaml
failed: [localhost] (item={'name': 'TLS Inspection Bypass - Google', 'description': 'Bypass TLS inspection to Google services.', 'custom_category': True, 'type': 'URL_CATEGORY', 'super_category': 'USER_DEFINED', 'db_categorized_urls': ['accounts.google.com', 'clients1.google.com', 'firebaseinstallations.googleapis.com', 'ogs.google.com', 'play.google.com', 'play.googleapis.com', 'www.googleadservices.com'], 'state': 'present'}) => 
    ansible_loop_var: item
    changed: false
    item:
        custom_category: true
        db_categorized_urls:
        - accounts.google.com
        - play.google.com
        description: Bypass TLS inspection to Google services.
        name: TLS Inspection Bypass - Google
        state: present
        super_category: USER_DEFINED
        type: URL_CATEGORY
    msg: 'URLCategoriesAPI.add_url_category() missing 1 required positional argument:
        ''urls'''
```
